# ================================
# BASIC CONFIGURATIONS
# ================================
debug: False
exp_name: DEBUG_scattering_map+clamping_Idt_FIX_SoftDice_augm_Vessels_
project_name: PRIUS           # Name of the WandB project
device: cuda
logging: True
on_polyaxon: False

# ================================
# DATA DIRECTORIES & PATHS
# ================================
base_folder_data_path: /mnt/projects/aorta_scan/random_simulated_ultrasound/
data_dir_real_us_cut_training: /mnt/projects/liver_scan/us_scans_Jun/2D_only/filtered/
data_dir_real_us_test: /home/farid/Desktop/phantom_simulated_data/  # TODO: Change to test set
data_dir_real_us_stopp_crit: /home/farid/Desktop/phantom_simulated_data/  # TODO: Check with Dani
output_path: ./checkpoints  # TODO: Change to NAS

# Paths for Polyaxon  # these are not used anymore
polyaxon_imgs_folder: /us_sim_sweeps/cactuss_end2end/data/CTs+labelmaps_cropped2/
polyaxon_masks_folder: /us_sim_sweeps/cactuss_end2end/data/CTs+labelmaps_cropped2/
polyaxon_folder_real_us: /us_sim_sweeps/cactuss_end2end/data/real_us/vessels/CUT_trainA_500
polyaxon_data_dir_real_us_test: /us_sim_sweeps/cactuss_end2end/data/real_us/vessels/GT_data_vessels_100/GT_data_vessels_testing/
polyaxon_data_dir_real_us_stopp_crit: /us_sim_sweeps/cactuss_end2end/data/real_us/vessels/GT_data_vessels_100/GT_data_vessels_stopp_crit/  # Subset of 20 images for stopping criterion after min_epochs

# ================================
# DATA LOADERS & MODELS
# ================================
dataloader_ct_labelmaps: ct_3d_labemaps_pose_dataset_torch.CT3DLabelmapPoseDataLoader
dataloader_real_us_test: real_us_pose_dataset_with_gt_torch.PoseRegressionDataset
module: poseRegressionEfficientNetSim_torch.PoseRegressionSim
inner_model: us_rendering_model_torch.UltrasoundRendering

# ================================
# TRAINING CONFIGURATIONS
# ================================
dropout: False
dropout_ratio: 0.0
seg_net_input_augmentations_noise_blur: True
cactuss_mode: False
warp_img: True
num_workers: 0  # Previously: 24
batch_size: 1
batch_size_manual: 1
inner_model_learning_rate: 0.0001
outer_model_learning_rate: 0.00001
scheduler: False
grad_clipping: False
min_epochs: 50  # Previously: 70
max_epochs: 200  # Previously: 200
early_stopping_patience: 5
validate_every_n_steps: 1  # Default: 50
stopping_crit_gt_imgs: True
plot_avg_seg_px_dff: True
epochs_only_cut: 0
epochs_only_seg_net: 0
epochs_check_stopp_crit: 50
use_idtB: True
log_default_renderer: True

# ================================
# (Optional) Commented Out Configurations
# ================================
# These configurations are commented out but kept for future reference.
# exp_name: DEBUG_scattering_map+clamping_freeze_renderer_idt_FIX_Monai_32-512_augm_noBlur_dropout_
# data_dir_real_us_test: /home/aorta-scan/dani/data/GT_doctor/stopping_criter_vessels/
# dataset: ct_3d_labemaps_dataset_torch.CT3DLabelmapDataset
# dataloader_real_us: real_us_dataset_torch.RealUSDataLoader
# global_learning_rate: 0.0001  # 5e-3
# lambda_G_loss: 0.5
# early_stopping_metric: val_loss_epoch  # val_loss  # default
# save_top_k: 1
# log_interval: 100  # default
# limit_train: 1.0  # default: 1.0
# limit_val: 1.0
