exp_name : discr+inner+outer_
project_name : cactuss_end2end-Segmentation         #the wandb project name
base_folder_data_path: /home/aorta-scan/dani/data/CTs+labelmaps_cropped/
# base_folder_data_path: /home/aorta-scan/dani/data/CTs+labelmaps_cropped_catheter/
labelmap_path : /ct_labelmap2/ #
data_dir_real_us : ./cut/datasets/aorta_us_8CTs/trainA_500
output_path : /home/aorta-scan/dani/repos/cactuss_end2end/checkpoints

module : segmentationUnetSimDiscr_torch.SegmentationSim

outer_model : UNet
inner_model : us_rendering_model_torch.UltrasoundRendering
# inner_model : us_rendering_catheter_model_torch.UltrasoundRendering

#dataset : ct_3d_labemaps_dataset_torch.CT3DLabelmapDataset
dataloader : ct_3d_labemaps_dataset_torch.CT3DLabelmapDataLoader
dataloader_real_us : real_us_dataset_torch.RealUSDataLoader
n_classes : 1
pred_label : 4    # 4-vessel, 6-kidney, 10 - catheter, 11-liver

num_workers : 1 #24


batch_size : 1
global_learning_rate: 0.005 # 5e-3

discr_model_learning_rate: 0.001  # def CUT is 5e-6, def LSGAN is 0.0002
inner_model_learning_rate: 0.0005
outer_model_learning_rate: 0.000
lambda_G_loss: 0.5

# early_stopping_metric : val_loss_epoch  #val_loss  #default
# save_top_k : 1
min_epochs : 20
max_epochs : 200
early_stopping_patience : 5
validate_every_n_steps : 1 #default is 50

# log_interval : 100 #default
# limit_train : 1.0 #1.0 default
# limit_val : 1.0

on_polyaxon : False
logging : False
polyaxon_folder : /us_sim_sweeps/cactuss_end2end/data/CTs+labelmaps_cropped/
polyaxon_folder_real_us : /us_sim_sweeps/segmentation/cut/aorta_us_8CTs/trainA_500

